#!/bin/bash

set -e

function display_menu() {
    echo "1. cut audio or video"
	 echo "2. add audio to video"
	 echo "3. change resolution of video"
	 echo "4. compress audio file"
	 echo "5. remove audio from video"
	 echo "6. extract audio from video"
	 echo "7. watch video/play audio"
	 echo "8. music behind still image"
	 echo "0. or ctrl+c to quit"
}

while true; do
    display_menu
	 read -r -p "select option: " choice
    case $choice in
        1)
				read -r -e -p "starting time (in HH:MM:SS.mmm format, default 00:00:00.000): " start
            start="${start:-00:00:00.000}"
            read -r -e -p "file to cut: " file
				default_duration=$(ffprobe -i "$file" -show_entries format=duration -sexagesimal -v quiet -of csv="p=0")
				read -r -e -p "ending time (in HH:MM:SS.mmm format, default is the video duration: $default_duration): " end
				end="${end:-$default_duration}"
				read -r -e -p "output: " output
            ffmpeg -ss "$start" -i "$file" -to "$end" -c copy "$output"
				vlc "$output"
				;;
        2)
            read -r -e -p "video: " video 
            read -r -e -p "audio: " audio
				read -r -e -p "output: " output
            ffmpeg -i "$video" -i "$audio" -c:v copy -map 0:v -map 1:a -y "$output"
				vlc "$output"
				;;
			3)
				read -r -e -p "video: " video
				read -r -e -p "resolution: " resolution
				read -r -e -p "output: " output
				ffmpeg -i "$video" -s "$resolution" -c:a copy "$output"
				vlc "$output"
				;; 
			 4)
				read -r -e -p "audio: " audio
				read -r -e -p "new bitrate: " bitrate
				read -r -e -p "output: " output
				ffmpeg -i "$audio" -ab "$bitrate" "$output"
				vlc "$output"
				;;
			 5)
				read -r -e -p "video: " video
				read -r -e -p "output: " output
				ffmpeg -i "$video" -an "$output"
				vlc "$output"
				;;
			 6)
				read -r -e -p "video: " video
				read -r -e -p "output: " output
				ffmpeg -i "$video" -vn "$output"
				vlc "$output"
				;;
			7) 
				read -r -e -p "media: " media
				vlc "$media"
				;;
			8) 
				read -r -e -p "image: " image
				read -r -e -p "audio: " audio
				read -r -e -p "output: " output
				ffmpeg -loop 1 -i "$image" -i "$audio" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -shortest "$output"
				vlc "$output"
				;;

			0)
				exit 
				;;
			*)
            echo "invalid choice. please select a valid option."
            ;;
    esac

    echo
done
